local palette <const> = {
    COLOR_BLANK               = 0x000000,
    COLOR_DEFAULT             = 0xDEDEDE,
    COLOR_DOT                 = 0xFFB897,
    COLOR_PACMAN              = 0xFFFF00,
    COLOR_BLINKY              = 0xFF0000,
    COLOR_PINKY               = 0xFFB8DE,
    COLOR_INKY                = 0x00FFDE,
    COLOR_CLYDE               = 0xFFB847,
    COLOR_FRIGHTENED          = 0x2121DE,
    COLOR_FRIGHTENED_BLINKING = 0xDEDEDE,
    COLOR_GHOST_SCORE         = 0x00FFDE,
    COLOR_EYES                = 0xDEDEDE,
    COLOR_CHERRIES            = 0xFF0000,
    COLOR_STRAWBERRY          = 0xFF0000,
    COLOR_PEACH               = 0xFFB847,
    COLOR_BELL                = 0xFFFF00,
    COLOR_APPLE               = 0xFF0000,
    COLOR_GRAPES              = 0x47B897,
    COLOR_GALAXIAN            = 0xFFFF00,
    COLOR_KEY                 = 0xFFFF00,
    COLOR_WHITE_BORDER        = 0xDEDEDE,
    COLOR_FRUIT_SCORE         = 0xFFB8DE,
}

return palette
