name: Nightly Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Website
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Build Soluna
        uses: ./soluna/.github/actions/soluna
        id: build
        with:
          soluna_path: "./soluna"
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install script dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install fonttools pillow
      - name: Generate Assets
        shell: bash
        run: |
          python .github/scripts/gen_sprites.py
          python .github/scripts/gen_fonts.py
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Enable Corepack
        shell: bash
        run: corepack enable
      - name: Install Website Dependencies
        shell: bash
        working-directory: website
        run: pnpm install --no-frozen-lockfile
      - name: Build Website
        shell: bash
        working-directory: website
        env:
          SITE_BASE: /${{ github.event.repository.name }}/
          SOLUNA_JS_PATH: ${{ steps.build.outputs.SOLUNA_JS_PATH }}
          SOLUNA_WASM_PATH: ${{ steps.build.outputs.SOLUNA_WASM_PATH }}
          SOLUNA_WASM_MAP_PATH: ${{ steps.build.outputs.SOLUNA_WASM_MAP_PATH }}
        run: pnpm run build
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: website/dist/
  deploy:
    name: Deploy to GitHub Pages
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
